[book]
authors = ["sitandr"]
language = "en"
multilingual = false
src = "src"
title = "Example book about Typst"

[preprocessor.typst-highlight]
#disable_inline = true
#typst_default = true
render = true